apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-delete-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pod-delete-operator
  template:
    metadata:
      labels:
        name: pod-delete-operator
    spec:
      serviceAccountName: pod-delete-operator
      containers:
        - name: pod-delete-operator
          # Replace this with the built image name
          image: srikrishnabh/pod-delete-operator:latest
          command:
          - pod-delete-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "pod-delete-operator"
